name: npm-publish
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    #- name: Diffset
    #  id: diffset
    #  uses: softprops/diffset@v1
    #  env:
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
    - name: Checkout branch
    #  if: steps.diffset.outputs.special_files
      uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
    #  if: steps.diffset.outputs.special_files
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://registry.npmjs.org'  

    - name: Build & Deploy to npm
    #  if: steps.diffset.outputs.special_files
      run: |
        yarn
        yarn docs
        npm publish --access public
      env:
        CI: true
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
